#pragma once

#include <vector>
#include <string>

enum class SCRIPT_TYPE
{
	ATTACKCOLLISIONSCRIPT,
	BELLSCRIPT,
	BISONDEATH,
	BISONHEADBUT,
	BISONHURT,
	BISONIDLE,
	BISONRUN,
	BISONSCRIPT,
	BISONSPAWN,
	BISONWALK,
	BLOODSCREENSCRIPT,
	BULLETSCRIPT,
	CAMERAMOVESCRIPT,
	CHESTIDLE,
	CHESTOPEN,
	CHESTOPENED,
	CHESTSCRIPT,
	COFFEESCRIPT,
	DIRECTIONALLIGHTSCRIPT,
	GCSCRIPT,
	GIGANTATTACK,
	GIGANTDEATH,
	GIGANTEND,
	GIGANTIDLE,
	GIGANTLOOP,
	GIGANTSCRIPT,
	GIGANTSPAWN,
	HDRSCRIPT,
	HPUISCRIPT,
	IMPATTACK,
	IMPDEATH,
	IMPHURT,
	IMPIDLE,
	IMPRUN,
	IMPSCRIPT,
	IMPSPAWN,
	ITEMOBJECTSCRIPT,
	JELLYFISHDEATH,
	JELLYFISHIDLE,
	JELLYFISHSCRIPT,
	JELLYFISHSPAWN,
	LEMURIANDEATH,
	LEMURIANFIREBALL,
	LEMURIANHURT,
	LEMURIANIDLE,
	LEMURIANPRE,
	LEMURIANRUN,
	LEMURIANSCRIPT,
	LEMURIANSPAWN,
	MEDIKITSCRIPT,
	MISSILESCRIPT,
	PLAYERFIRE,
	PLAYERIDLE,
	PLAYERJUMP,
	PLAYERMOVE,
	PLAYERROLL,
	PLAYERRUN,
	PLAYERSCRIPT,
	PLAYERSKILL,
	SCREENUISCRIPT,
	SHRINESCRIPT,
	SUBATTACK,
	SUBDEATH,
	SUBIDLE,
	SUBSCRIPT,
	SUBSPAWN,
	SUBWALK,
	SUMMON1SCRIPT,
	SUMMON2SCRIPT,
	SUMMON3SCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
